on:
  push:
    branches:
      - main
      - devel
  pull_request:

name: R-CMD-check-bioc

jobs:
  check:
    runs-on: ubuntu-latest
    container: ${{ matrix.config.image }}

    name: ${{ matrix.config.bioc }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - { bioc: 'release', image: 'bioconductor/bioconductor_docker:RELEASE_3_23' }
          - { bioc: 'devel',   image: 'bioconductor/bioconductor_docker:devel'         }

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      NOT_CRAN: true

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::BiocCheck, any::rcmdcheck
          needs: check
          cache: true

      - name: R CMD CHECK
        uses: r-lib/actions/check-r-package@v2
        with:
          args: 'c("--no-manual", "--no-vignettes", "--timings")'
          error-on: '"error"'

      - name: BiocCheck
        shell: Rscript {0}
        run: |
          BiocCheck::BiocCheck(
            package        = ".",
            `new-package`  = FALSE,
            `no-check-bioc-help` = TRUE
          )
